included: # paths to include during linting. `--path` is ignored if present.
- Sources
excluded:
- Sources/BushelUI/Welcome/PurchaseView.swift
# Customize specific rules
missing:
  severity: error

partial:
  severity: error

unused:
  severity: none

missing_comment:
  severity: error
  
json_comment_rule:
  severity: none