name: FloxBx
options:
  bundleIdPrefix: com.brightdigit
  deploymentTarget:
    watchOS: 7.0
    iOS: 14.0
    macOS: 11.0
settings:
  DEVELOPMENT_TEAM: MLT7M394S7
  CODE_SIGN_IDENTITY: "Apple Development"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  bundleIdPrefix: com.brightdigit
  PRODUCT_NAME: FloxBx
  LINT_MODE: ${LINT_MODE}
packages:
  FloxBxUI:
    path: ./Packages/FloxBxKit
targets:
  FloxBx.watchkitapp.watchkitextension:
    type: watchkit2-extension
    platform: watchOS
    dependencies:
      - package: FloxBxUI
    sources:
      - path: "Support/watchOS/Extension"
        name: Extension
        group: Support/watchOS
      - path: "Shared"
    info:
      path: Support/watchOS/Extension/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
        NSExtension:
          NSExtensionAttributes:
            WKAppBundleIdentifier: com.brightdigit.FloxBx.watchkitapp
          NSExtensionPointIdentifier: com.apple.watchkit
        WKRunsIndependentlyOfCompanionApp: true
    entitlements:
      path: Support/watchOS/Extension/watchOS.entitlements
      properties:
        com.apple.developer.applesignin: 
          - Default
          #aps-environment: development
          #com.apple.developer.siri: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.application-groups:
          - group.com.brightdigit.FloxBx
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.brightdigit.FloxBx
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.FloxBx.watchkitapp.watchkitextension
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.FloxBx.watchkitapp.watchkitextension
  FloxBx.watchkitapp:
    type: application.watchapp2
    platform: watchOS
    scheme: {}
    dependencies:
      - target: "FloxBx.watchkitapp.watchkitextension"
    sources:
      - path: "Support/watchOS/Application"
        name: Application
        group: Support/watchOS
      - path: "Shared/Assets.xcassets"
    info:
      path: Support/watchOS/Application/Info.plist
      properties:
        WKWatchKitApp: true
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
        WKCompanionAppBundleIdentifier: com.brightdigit.FloxBx
    entitlements:
      path: Support/watchOS/Application/watchOS.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.brightdigit.FloxBx
    settings:
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.FloxBx.watchkitapp
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.FloxBx.watchkitapp
  FloxBx.iOS:
    type: application
    platform: iOS
    scheme: {}
    dependencies:
      - package: FloxBxUI
      - target: "FloxBx.watchkitapp"
    sources:
      - path: "Support/iOS"
        name: iOS
        group: Support
      - path: "Shared"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.FloxBx
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.FloxBx
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.FloxBx
    info:
      path: Support/iOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
    entitlements:
      path: Support/iOS/iOS.entitlements
      properties:
        com.apple.developer.applesignin: 
          - Default
        aps-environment: development
        #aps-environment: development
        #com.apple.developer.siri: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.application-groups:
          - group.com.brightdigit.FloxBx
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.brightdigit.FloxBx
    postBuildScripts:
    - path: Packages/FloxBxKit/scripts/lint.sh
      name: Lint
      basedOnDependencyAnalysis: false  
  FloxBx.macOS:
    type: application
    platform: macOS
    scheme: {}
    dependencies:
      - package: FloxBxUI
    info:
      path: Support/macOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
    sources:
      - path: "Support/macOS"
        name: macOS
        group: Support
      - path: "Shared"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ${bundleIdPrefix}.FloxBx
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: match Development com.brightdigit.FloxBx macos
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: match AppStore com.brightdigit.FloxBx macos
      path: Support/macOS/Info.plist
      properties:
        ITSAppUsesNonExemptEncryption: false
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleDisplayName: FloxBx
    entitlements:
      path: Support/macOS/macOS.entitlements
      properties:
        com.apple.developer.applesignin: 
          - Default
        #aps-environment: development
        #com.apple.developer.siri: true
        com.apple.security.network.client: true
        com.apple.security.app-sandbox: true
        com.apple.security.files.user-selected.read-only: true
        com.apple.security.application-groups:
          - group.com.brightdigit.FloxBx
        keychain-access-groups:
          - $(AppIdentifierPrefix)com.brightdigit.FloxBx
    postBuildScripts:
    - path: Packages/FloxBxKit/scripts/lint.sh
      name: Lint
      basedOnDependencyAnalysis: false  