# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :prepare_development do 
  match({
    app_identifier: ["com.brightdigit.FloxBx.watchkitapp.watchkitextension","com.brightdigit.FloxBx","com.brightdigit.FloxBx.watchkitapp"]
  })
  match({
    app_identifier: ["com.brightdigit.FloxBx"],
    platform: "macos"
  })
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    build_app(scheme: "FloxBx.iOS")
    upload_to_testflight
  end
end

platform :mac do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    match(type: "appstore", readonly: is_ci)
    build_app(scheme: "FloxBx.macOS")
    upload_to_testflight
  end
end