#if !canImport(ObjectiveC)
  import XCTest

  extension PrchTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PrchTests = [
      ("testPrch", testPrch)
    ]
  }

  public func __allTests() -> [XCTestCaseEntry] {
    return [
      testCase(PrchTests.__allTests__PrchTests)
    ]
  }
#endif
